### ISSUE TITLE
Delete everything.

### ISSUE THREAD

**Issue by PotcFdk** [TheKeyLimePie/hacktober#5]
Cheatoberfest is üver! Entfern thu evidenz.

```
                      "Prelude"

  Somewhere out there in the vast nothingness of space,
          Somewhere far away in space and time.
Staring upward at the gleaming stars in the obsidian sky
  We're marooned on a small island, in an endless sea.
   Confined to a tiny spit of sand, unable to escape
      But tonight, on this small planet, on Earth
          We're going to rock civilization. 
```

**Comment by TheKeyLimePie** [comment]
I took notice of your request and I decided to discuss the current situation with our research staff.
We arrived to the conclusion that our current research in 

> effektive Leistungsoptimierungsstrategien mit Zuhilfenahme von Linear Discriminant Analysis (LDA) in Hinblick auf cremigere Käsesoßen auf mexikanischem Maismehl-Salzgebäck

is not yet fulfilled due to a lack of interdisciplinary cooperation. From this it follows that we won't remove this data.

We apologise for any inconvenience this decision may cause.
